# Generated by Django 5.1.3 on 2024-11-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_palette_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='favorite_colors',
            field=models.BooleanField(),
        ),
    ]
